# __Matrices et Numpy__ :
 

Définition de la matrice en numpy :

In [21]:
import numpy as np
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

dimension de la matrice : 

In [22]:
A.shape

(3, 2)

Transposée de la matrice :

In [23]:
B = A.T
B.shape

(2, 3)

Matrice unitaire :


In [29]:
C = 2 * np.ones((3,2))
C

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

Somme de matrices :


In [25]:
A + C

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

Multiplication  elements * elements de 2 Matrices , attention au dimension des matrices (elles doivent être similaire A = n x p et C = n x p)

In [30]:
A * C

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.]])

Produit matriciel de deux matrices , nxp et pxm est une conditions obligatoire, on obtient une matrice de demiension  : n x m


In [31]:
A.dot(B)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])